name: CI

on:
    push:

jobs:
    sample-job: 
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v3
        
        - name: Run shell commands
          run: |
            echo Testing action
            ls -alh
            