name: CI

on:
    # workflow_dispatch:
    pull_request:
    push:
        branches:
            - master
            - main

jobs:
    sample-job: 
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v3

        - name: Run shell commands
          run: |
            echo Testing action
            ls -alh
            